#!/usr/bin/env python3
"""Render all matching clips as a local HTML gallery and Obsidian watchlist.

Uses the library's search index; never downloads media or starts a web server.
Only files bearing this generator's marker may be replaced.
"""
from __future__ import annotations

import argparse
import html
import json
import os
from pathlib import Path
import re
import sqlite3
import sys
import tempfile
from urllib.parse import quote, urlparse


MARKER = "<!-- Generated by INDEXX indexx_watch.py; regenerate from search. -->"
SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")
VIDEO_SUFFIXES = {".mp4", ".m4v", ".webm", ".ogv", ".mov"}
STYLE = """
:root { color-scheme: light dark; font: 16px/1.5 system-ui, sans-serif; }
body { max-width: 1100px; margin: 0 auto; padding: 2rem 1rem; }
h1 { margin-bottom: .4rem; } h2 { font-size: 1.2rem; margin: 0 0 .6rem; }
.summary, .meta { opacity: .8; } .gallery { display: grid; gap: 1.5rem;
  grid-template-columns: repeat(auto-fit, minmax(min(100%, 320px), 1fr)); }
article { border: 1px solid #8887; border-radius: 12px; padding: 1rem; overflow-wrap: anywhere; }
video { display: block; width: auto; height: auto; max-width: 100%; max-height: 480px;
  margin-inline: auto; background: #111; border-radius: 6px; }
.unavailable { padding: 2rem 1rem; border: 1px dashed #888; text-align: center; }
.links { display: flex; flex-wrap: wrap; gap: 1rem; } a { color: inherit; }
"""


def plain(value: object) -> str:
    return " ".join(str(value if value is not None else "").split())


def markdown_text(value: object) -> str:
    # Escape HTML first, then Markdown syntax. Imported text cannot add links,
    # embeds, headings, or HTML elements to the generated document.
    return re.sub(r"([\\`*_{}\[\]()#+!|~>-])", r"\\\1", html.escape(plain(value), quote=False))


def local_path(root: Path, raw: object) -> Path | None:
    if raw is None or raw == "":
        return None
    if not isinstance(raw, (str, Path)):
        raise ValueError("Local result paths must be strings or paths")
    value = str(raw)
    if any(ord(char) < 32 for char in value):
        raise ValueError("Local result paths cannot contain control characters")
    path = Path(value).expanduser()
    if ".." in path.parts:
        raise ValueError(f"Local result path contains parent traversal: {value}")
    path = (root / path).resolve() if not path.is_absolute() else path.resolve()
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"Local result path escapes the library: {value}") from exc
    return path


def clip_url(raw: object, item_id: str) -> str | None:
    if not isinstance(raw, str):
        return None
    parsed = urlparse(raw)
    match = re.fullmatch(r"/(p|reel|tv)/([A-Za-z0-9_-]+)/?", parsed.path)
    if (parsed.scheme != "https" or parsed.netloc not in ("instagram.com", "www.instagram.com")
            or not match or match.group(2) != item_id):
        return None
    # The clip identity is sufficient; omit tracking/query data from links.
    return f"https://www.instagram.com/{match.group(1)}/{item_id}/"


def relative_url(path: Path, output: Path) -> str:
    return quote(Path(os.path.relpath(path, output)).as_posix(), safe="/")


def output_path(root: Path, name: str, suffix: str) -> Path:
    path = root / "wiki" / "views" / (name + suffix)
    current = root
    for part in path.relative_to(root).parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"Watchlist output cannot use symlinks: {current}")
        if current != path and current.exists() and not current.is_dir():
            raise ValueError(f"Expected an output directory: {current}")
    if path.exists():
        if not path.is_file() or not path.read_bytes().startswith((MARKER + "\n").encode()):
            raise ValueError(f"Refusing to overwrite a file not generated by indexx_watch.py: {path}")
    return path


def coverage_text(coverage: dict) -> str:
    def count(key: str) -> int | None:
        value = coverage.get(key)
        return value if isinstance(value, int) and not isinstance(value, bool) and value >= 0 else None
    reviewed, total = count("people_reviewed"), count("catalog_total")
    if reviewed is None or total is None or reviewed > total:
        return "People annotation coverage is unknown; results do not establish that every clip has been reviewed."
    text = f"People annotations reviewed for {reviewed} of {total} catalog clips."
    if reviewed < total:
        text += f" {total - reviewed} clips are unreviewed and may contain additional people."
    return text


def stage_file(path: Path, data: bytes) -> Path:
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
        return Path(temporary)
    except BaseException:
        if os.path.exists(temporary):
            os.unlink(temporary)
        raise


def publish_pair(root: Path, name: str, documents: dict[Path, bytes], originals: dict[Path, bytes | None]) -> None:
    """Stage both formats and restore prior bytes on a failed publication.

    Two file replacements are not an atomic transaction across a process crash.
    Already-staged rollback copies handle ordinary write/replacement failures.
    """
    def unchanged(path: Path, expected: bytes | None) -> None:
        output_path(root, name, path.suffix)
        current = path.read_bytes() if path.exists() else None
        if current != expected:
            raise ValueError(f"Watchlist destination changed; regenerate after other writers stop: {path}")

    staged, backups, published, retained = {}, {}, [], set()
    try:
        for path in documents:
            unchanged(path, originals[path])
        next(iter(documents)).parent.mkdir(parents=True, exist_ok=True)
        for path, data in documents.items():
            staged[path] = stage_file(path, data)
        for path, data in originals.items():
            if data is not None:
                backups[path] = stage_file(path.with_name(path.name + ".rollback"), data)
        # Recheck the complete pair after staging, before exposing either version.
        for path in documents:
            unchanged(path, originals[path])
        try:
            for path in documents:
                unchanged(path, originals[path])
                os.replace(staged[path], path)
                published.append(path)
        except BaseException as exc:
            rollback_errors = []
            for path in reversed(published):
                try:
                    # Preserve a concurrent edit rather than replacing it during recovery.
                    unchanged(path, documents[path])
                    if originals[path] is None:
                        path.unlink()
                    else:
                        os.replace(backups[path], path)
                except (OSError, ValueError) as recovery_error:
                    rollback_errors.append(f"{path}: {recovery_error}")
                    if path in backups:
                        retained.add(backups[path])
            if rollback_errors:
                recovery = "; ".join(str(path) for path in retained) or "no previous files existed"
                raise OSError("Watchlist update and rollback failed. Original copies retained at " + recovery
                              + ". Recovery errors: " + "; ".join(rollback_errors)) from exc
            raise
    finally:
        for temporary in (*staged.values(), *backups.values()):
            if temporary not in retained and temporary.exists():
                temporary.unlink()


def render_watchlist(root: Path, report: dict, name: str = "watchlist", title: str = "INDEXX watchlist") -> dict:
    root = root.expanduser().resolve()
    if not root.is_dir():
        raise ValueError("The library root must be an existing directory")
    if not isinstance(name, str) or not SLUG.fullmatch(name):
        raise ValueError("--name must be a lowercase slug such as watchlist or weekend-clips")
    results = report.get("results")
    if not isinstance(results, list) or not all(isinstance(item, dict) for item in results):
        raise ValueError("Search results must be a list of clip objects")
    if report.get("total", len(results)) != len(results):
        raise ValueError("Watchlists require all search results; request search with limit=None")
    html_path, md_path = output_path(root, name, ".html"), output_path(root, name, ".md")
    originals = {path: path.read_bytes() if path.exists() else None for path in (html_path, md_path)}
    output = html_path.parent
    coverage = report.get("coverage") if isinstance(report.get("coverage"), dict) else {}
    coverage_summary = coverage_text(coverage)
    snapshot = "Index snapshot: " + (plain(report.get("indexed_at")) or "unknown") + ". This is a saved view. Rebuild the search index and regenerate this watchlist after library changes."
    cards, entries, playable = [], [], 0
    for item in results:
        item_id = plain(item.get("id"))
        heading = plain(item.get("title")) or item_id or "Untitled clip"
        uploader = plain(item.get("handle")) or "Unknown uploader"
        if uploader != "Unknown uploader":
            uploader = "@" + uploader.lstrip("@")
        people = item.get("people") or []
        if not isinstance(people, list) or not all(isinstance(person, dict) for person in people):
            raise ValueError("People annotations must be a list of objects")
        people_text = "; ".join(
            f"{plain(person.get('name')) or plain(person.get('id')) or 'Unnamed person'} ({plain(person.get('role')) or 'role unspecified'})"
            for person in people
        ) or "No person annotations in this result"
        local_path(root, item.get("media_path"))
        video = local_path(root, item.get("video_path"))
        source = local_path(root, item.get("source_path"))
        url = clip_url(item.get("url"), item_id)
        html_links, md_links = [], []
        if url:
            html_links.append(f'<a href="{html.escape(url, quote=True)}" rel="noreferrer">View on Instagram</a>')
            md_links.append(f"[View on Instagram](<{url}>)")
        if source is not None and source.is_file() and source.suffix.lower() == ".md":
            href = relative_url(source, output)
            html_links.append(f'<a href="{html.escape(href, quote=True)}">Wiki source</a>')
            md_links.append(f"[Wiki source](<{href}>)")
        available = video is not None and video.is_file() and video.stat().st_size > 0 and video.suffix.lower() in VIDEO_SUFFIXES
        if available:
            playable += 1
            href = relative_url(video, output)
            poster = local_path(root, video.with_name("poster.jpg"))
            poster_attribute = ''
            if poster.is_file() and poster.stat().st_size > 0:
                poster_attribute = f' poster="{html.escape(relative_url(poster, output), quote=True)}"'
            player = f'<video controls preload="metadata" src="{html.escape(href, quote=True)}"{poster_attribute}><a href="{html.escape(href, quote=True)}">Open local video</a></video>'
            vault_path = video.relative_to(root).as_posix()
            if re.fullmatch(r"[A-Za-z0-9_./ -]+", vault_path):
                markdown_video = f"![[{vault_path}]]"
            else:
                markdown_video = f"[Open local video](<{href}>)"
        else:
            player = '<p class="unavailable">Local video unavailable.</p>'
            markdown_video = "Local video unavailable."
        excerpt = plain(item.get("excerpt"))
        meta = f"Uploader: {uploader} · Clip: {item_id or 'unknown'} · Type: {plain(item.get('type')) or 'unknown'}"
        cards.append(
            '<article><h2>' + html.escape(heading) + '</h2>' + player
            + '<p class="meta">' + html.escape(meta) + '</p><p>People: ' + html.escape(people_text) + '</p>'
            + ('<p>' + html.escape(excerpt) + '</p>' if excerpt else '')
            + '<p class="links">' + ' '.join(html_links) + '</p></article>'
        )
        entry = ["## " + markdown_text(heading), markdown_video, markdown_text(meta), "People: " + markdown_text(people_text)]
        if excerpt:
            entry.append(markdown_text(excerpt))
        if md_links:
            entry.append(" · ".join(md_links))
        entries.append("\n\n".join(entry))
    summary = f"{len(results)} matching clips · {playable} local videos available"
    warnings = report.get("warnings") or []
    if not isinstance(warnings, list):
        raise ValueError("Search warnings must be a list")
    warning_html = '<ul>' + ''.join('<li>' + html.escape(plain(warning)) + '</li>' for warning in warnings) + '</ul>' if warnings else ''
    warning_md = "\n\n" + "\n".join("- " + markdown_text(warning) for warning in warnings) if warnings else ""
    html_document = (
        MARKER + '\n<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; media-src \'self\' file:; img-src \'self\' file:; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'">'
        '<title>' + html.escape(plain(title)) + '</title><style>' + STYLE + '</style></head><body>'
        '<h1>' + html.escape(plain(title)) + '</h1><p class="summary">' + html.escape(summary) + '</p><p>'
        + html.escape(coverage_summary) + '</p><p class="meta">' + html.escape(snapshot) + '</p>' + warning_html
        + '<main class="gallery">' + (''.join(cards) if cards else '<p>No matching clips.</p>') + '</main></body></html>\n'
    )
    markdown_document = MARKER + "\n# " + markdown_text(title) + "\n\n" + markdown_text(summary) + "\n\n" + markdown_text(coverage_summary) + "\n\n" + markdown_text(snapshot) + warning_md + "\n\n" + ("\n\n".join(entries) if entries else "No matching clips.") + "\n"
    # Validate all inputs and both existing destinations before any output writes.
    publish_pair(root, name, {html_path: html_document.encode("utf-8"), md_path: markdown_document.encode("utf-8")}, originals)
    return {"html_path": str(html_path), "markdown_path": str(md_path), "count": len(results), "playable": playable, "coverage": coverage}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, help="Absolute local library root")
    parser.add_argument("--person")
    parser.add_argument("--role")
    parser.add_argument("--uploader")
    parser.add_argument("--text", default="", help="Full-text query")
    parser.add_argument("--type", dest="media_type")
    parser.add_argument("--name", default="watchlist", help="Output filename slug under wiki/views")
    args = parser.parse_args()
    try:
        from indexx_search import search
        root = Path(args.root).expanduser()
        if not root.is_absolute():
            raise ValueError("--root must be an absolute library path")
        report = search(root, query=args.text, person=args.person, role=args.role, uploader=args.uploader, media_type=args.media_type, limit=None)
        title_parts = [args.person or "INDEXX watchlist"]
        if args.role:
            title_parts.append(args.role)
        if args.uploader:
            title_parts.append("Uploader: @" + args.uploader.lstrip("@"))
        if args.media_type:
            title_parts.append(args.media_type)
        if args.text:
            title_parts.append('Search: "' + args.text + '"')
        result = render_watchlist(root, report, name=args.name, title=" · ".join(title_parts))
        print(json.dumps(result, indent=2))
        return 0
    except (ImportError, OSError, ValueError, sqlite3.Error) as exc:
        print(f"Watchlist stopped: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
